### PR TITLE
Add tests for field operations

### PR DESCRIPTION
**Pull request by AaronFeickert**
Adds simple tests for field operations by showing that multiplication, division, and addition invert as expected. Exports the relevant functions to make them visible to the test runner.

### CODE REVIEW

**Comment by benjreinhart** [comment]
Hey Aaron, appreciate the contribution! We are currently testing through the public interfaces which should cover the desired behavior. However, given the sensitively of this code, I am open to testing some of the implementation details for added confidence.

If we do test these internal functions, then my preference would be to move them into a separate file which is imported by index.ts. That way, we keep the public interface only for the functions that we intend to export. Thoughts?

**Comment by AaronFeickert** [comment]
I agree that moving the polynomial and field operations to a separate file could be useful. This would allow for much broader test coverage, which could include specific unit tests for polynomial evaluation, interpolation, and the like. It's not immediately clear that the existing public-interface tests exercise all the underlying functionality in a comprehensive way.

Depending on how standalone you'd like the library to be, it may also be beneficial to include a test that specifically checks that the lookup tables are correct for the given generator and irreducible polynomial. Right now, the reader must both manually check that the tables were copied correctly and determine if the original source produced them correctly. The tests I added aren't comprehensive in this way.

**Comment by asta-li** [comment]
Thank you for this contribution as well. I second Ben's opinion: I also prefer not to expose these internal functions as a part of the public interface of this library.

**Comment by AaronFeickert** [comment]
Would a refactor of the field and polynomial operations (with tests of the new public interfaces for this) be suitable for this PR?

**Comment by asta-li** [comment]
I would prefer to test via the public interfaces of this library in order to avoid unnecessarily expanding the support surface of internal implementation details. If you are looking to increase test coverage, would it be possible to add tests that rely on the public interfaces?

If it is much more clear and comprehensive to test the internal implementation details, we could consider refactoring the operations into a separate file and testing as you suggest. We should ensure they do not become a part of the external library interface, and that preconditions are strongly enforced now that the helper functions can potentially be taken out of their original context.

**Comment by AaronFeickert** [comment]
As noted above, I think that tests for the field and polynomial operations (which are currently internal) are very important, particularly because the field lookup tables are from an external source that itself did not have any correctness tests.

For this reason, I agree that moving those functions to separate files, making them visible for the test runner, and then providing tests for them. While it may be suboptimal to expose things like the lookup tables, they really should be tested.

**Review by asta-li — CHANGES_REQUESTED** [review]
Requesting that we do not expand the public interface (more in comment thread above)

**Comment by AaronFeickert** [comment]
> Requesting that we refactor into separate files (more in comment thread above)

What would be the most idiomatic way to establish field/polynomial function visibility (via a refactor) to the test runner without exposing those functions to your external interface?

**Comment by asta-li** [comment]
You can create a new file `src/field-operations.ts` that `index.ts` can import. Then that file can be tested via `test/field-operations.test.js`. That should enable testing while preserving the existing external interface.

**Comment by AaronFeickert** [comment]
Sounds good @asta-li! I think such a change will help to assert confidence in the correct of the underlying arithmetic operations, and could prove useful for others who wish to use that part of the library.

Will close this PR since the scope has now changed.

**Pull request closed without merging**
